<div id="signup-form">
 
<div id="form-container">  
  
<form action="http://generationswithvision.us2.list-manage1.com/subscribe/post" method="POST">
<input type="hidden" name="u" value="641279d927137eec6730e767f">
<input type="hidden" name="id" value="ae104eb7d4">

<div id="mergeTable" class="mergeTable">

<ul id="form">  

<li>
<div class="mergeRow dojoDndItem mergeRow-email" id="mergeRow-0">

<label for="MERGE0"><strong>Email Address</strong> <span class="asterisk">*</span></label>
<div class="field-group">
    <input type="email" autocapitalize="off" autocorrect="off" name="MERGE0" id="MERGE0" size="25" value="">
</div><!--End .field-group-->
</div><!--End #mergeRow-->
  </li>

<li>
<div class="mergeRow dojoDndItem mergeRow-text" id="mergeRow-1">
<label for="MERGE1">First Name</label>
<div class="field-group">
    <input type="text" name="MERGE1" id="MERGE1" size="25" value="">
</div><!--End .field-group-->
</div><!--End #mergeRow-->
  </li>

<li>
<div class="mergeRow dojoDndItem mergeRow-text" id="mergeRow-2">
<label for="MERGE2">Last Name</label>
<div class="field-group">
    <input type="text" name="MERGE2" id="MERGE2" size="25" value="">
</div><!--End .field-group-->
</div><!--End #mergeRow-->
  </li>


<li>
<div class="mergeRow dojoDndItem mergeRow-text" id="mergeRow-4">
<label for="MERGE4">Address</label>
<div class="field-group">
    <input type="text" name="MERGE4" id="MERGE4" size="25" value="">
</div><!--End .field-group-->
</div><!--End #mergeRow-->
  </li>

<li>
<div class="mergeRow dojoDndItem mergeRow-text" id="mergeRow-3">
<label for="MERGE3">City</label>
<div class="field-group">
    <input type="text" name="MERGE3" id="MERGE3" size="25" value="">
</div><!--End .field-group-->
</div><!--End #mergeRow-->
  </li>

<li>
<div class="mergeRow dojoDndItem mergeRow-text" id="mergeRow-6">
<label for="MERGE6">State</label>
<div class="field-group">
    <input type="text" name="MERGE6" id="MERGE6" size="25" value="">
</div><!--End .field-group-->
</div><!--End #mergeRow-->
  </li>
  
  
<li>
<div class="mergeRow dojoDndItem mergeRow-text" id="mergeRow-7">
<label for="MERGE7">Zip</label>
<div class="field-group">
    <input type="text" name="MERGE7" id="MERGE7" size="25" value="">
</div><!--End .field-group-->
</div><!--End #mergeRow-->
 </li>
  
  
<li>
<div id="interestTable">
    
<div id="mergeRow-100-7393" class="mergeRow dojoDndItem mergeRowHidden mergeRow-interests-hidden" style="display:none;">
			<label>Referred by</label>
	        <div class="field-group groups">
<ul class="interestgroup_field" id="interestgroup_field_455445"><li class="interestgroup_row"><input type="checkbox" id="group_1" name="group[7393][1]" value="1">&nbsp;<label for="group_1">hslda</label></li><li class="interestgroup_row"><input type="checkbox" id="group_2" name="group[7393][2]" value="1">&nbsp;<label for="group_2">wnd</label></li></ul>
            </div><!--End .field-group-->

</div><!--End #mergeRow-100-7393-->
</div><!--End #interestTable-->
  </li>    

<br>


<div class="submit_container">
<input type="submit" class="button" name="submit" value="Subscribe to list">
</div><!--End #submit_container-->
 
</div><!--End #mergeTable-->
</ul><!--End #form-->

</form>


</div><!--End #form-container-->
</div><!--End #signup-form-->

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-35158919-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

		
</body>
</html>