<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
<meta charset="UTF-8" />

<title>Register for the Conference! | Family Economics</title>
	
<link rel="profile" href="http://gmpg.org/xfn/11" />


<link rel="stylesheet" type="text/css" media="all" href="styles/mainstyles.css" />
<link rel="icon" href="http://www.familyeconomics.com/wp-content/themes/family-economics/images/favicon.png" type="image/png">

<script src="http://www.familyeconomics.com/wp-content/themes/family-economics/js/jquery.js" type="text/javascript"></script>
<script src="http://www.familyeconomics.com/wp-content/themes/family-economics/js/main.js" type="text/javascript"></script>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"></script>
<script src="http://malsup.github.com/jquery.form.js"></script>
<script src="scripts/jquery.easing.1.3.js"></script>
<script src="scripts/stickysidebar.jquery.min.js"></script>

<link rel="pingback" href="http://www.familyeconomics.com/xmlrpc.php" />

<meta name='robots' content='noindex,nofollow' />
<link rel="alternate" type="application/rss+xml" title="Family Economics &raquo; Feed" href="http://www.familyeconomics.com/feed/" />
<link rel="alternate" type="application/rss+xml" title="Family Economics &raquo; Comments Feed" href="http://www.familyeconomics.com/comments/feed/" />
<link rel='stylesheet' id='admin-bar-css'  href='http://www.familyeconomics.com/wp-includes/css/admin-bar.css?ver=3.4.2' type='text/css' media='all' />
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://www.familyeconomics.com/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://www.familyeconomics.com/wp-includes/wlwmanifest.xml" /> 
<link rel='prev' title='Speakers' href='http://www.familyeconomics.com/speakers/' />
<link rel='next' title='Schedule' href='http://www.familyeconomics.com/schedule/' />
<meta name="generator" content="WordPress 3.4.2" />
<link rel='canonical' href='http://www.familyeconomics.com/facility-accommodations/' />



</head>

<body>