CREATE TABLE REGISTRATION
(
registration_id int NOT NULL AUTO_INCREMENT,
family_id int,
payment_id int,
coupon_id int,
registration_type varchar(255) NOT NULL,
attendee_number int NOT NULL,
days_attending varchar(255),
contact_address_1 varchar(255),
contact_address_2 varchar(255),
contact_city varchar(255),
contact_state varchar(255),
contact_zip varchar(255),
contact_phone varchar(255),
contact_alt_phone varchar(255),
contact_email varchar(255),
billing_address_1 varchar(255),
billing_address_2 varchar(255),
billing_city varchar(255),
billing_state varchar(255),
billing_zip varchar(255),
billing_phone varchar(255),
billing_alt_phone varchar(255),
billing_email varchar(255),
referral varchar(255),
is_complete int NOT NULL
PRIMARY KEY (registration_id),
FOREIGN KEY (family_id) REFERENCES FAMILY(family_id),
FOREIGN KEY (payment_id) REFERENCES PAYMENT(payment_id),
FOREIGN KEY (coupon_id) REFERENCES COUPON(coupon_id)
)